### ISSUE TITLE
NotImplementedError after running "python get404.py"

### ISSUE THREAD

**Issue by evjak** [TimurNurlygayanov/qa_launchpad_weekly_reports#2]
Steps to reproduce:
1. Install all packages from requirements.txt
2. Run "python get404.py"

Expected result:
App runned

Actual result:
(web404) esikachev@Evgenys-MacBook-Pro:[~/qa_launchpad_weekly_reports/web404]$ python get404.py
Processing |                                | 0/192Traceback (most recent call last):
  File "get404.py", line 161, in <module>
    qsize = results_queue.qsize()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 143, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError

**Comment by TimurNurlygayanov** [comment]
Fixed. Now we have the list of requirements.

Thank you!
